language: node_js

node_js:
  - "6.2"

sudo: required

before_script:
  - sudo apt-key add test/vendors/matrix-repo-key.asc
  - echo "deb http://matrix.org/packages/debian jessie main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y curl coturn python-lxml python-jinja2 python-bleach matrix-synapse matrix-synapse-angular-client python-ldap3 pwgen
  - sudo mkdir -p /data
  - sudo cp -a test/vendors/start.sh /start.sh && sudo chmod +x /start.sh
  - export SERVER_NAME=zboxapp.dev && export REPORT_STATS=no && sudo -E /start.sh generate
  - sudo cp -af test/vendors/homeserver.yaml /data/homeserver.yaml
  - sudo nohup /start.sh start &
  - npm install

script:
  - npm run test
